# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexandr/Desktop/cprojects/compiler/university_compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexandr/Desktop/cprojects/compiler/university_compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexandr/Desktop/cprojects/compiler/university_compiler/CMakeFiles /home/alexandr/Desktop/cprojects/compiler/university_compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexandr/Desktop/cprojects/compiler/university_compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

source/src/PascalCompiler/Grammar/Nonterminals.o: source/src/PascalCompiler/Grammar/Nonterminals.cpp.o
.PHONY : source/src/PascalCompiler/Grammar/Nonterminals.o

# target to build an object file
source/src/PascalCompiler/Grammar/Nonterminals.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/Grammar/Nonterminals.cpp.o
.PHONY : source/src/PascalCompiler/Grammar/Nonterminals.cpp.o

source/src/PascalCompiler/Grammar/Nonterminals.i: source/src/PascalCompiler/Grammar/Nonterminals.cpp.i
.PHONY : source/src/PascalCompiler/Grammar/Nonterminals.i

# target to preprocess a source file
source/src/PascalCompiler/Grammar/Nonterminals.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/Grammar/Nonterminals.cpp.i
.PHONY : source/src/PascalCompiler/Grammar/Nonterminals.cpp.i

source/src/PascalCompiler/Grammar/Nonterminals.s: source/src/PascalCompiler/Grammar/Nonterminals.cpp.s
.PHONY : source/src/PascalCompiler/Grammar/Nonterminals.s

# target to generate assembly for a file
source/src/PascalCompiler/Grammar/Nonterminals.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/Grammar/Nonterminals.cpp.s
.PHONY : source/src/PascalCompiler/Grammar/Nonterminals.cpp.s

source/src/PascalCompiler/Grammar/Terminals.o: source/src/PascalCompiler/Grammar/Terminals.cpp.o
.PHONY : source/src/PascalCompiler/Grammar/Terminals.o

# target to build an object file
source/src/PascalCompiler/Grammar/Terminals.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/Grammar/Terminals.cpp.o
.PHONY : source/src/PascalCompiler/Grammar/Terminals.cpp.o

source/src/PascalCompiler/Grammar/Terminals.i: source/src/PascalCompiler/Grammar/Terminals.cpp.i
.PHONY : source/src/PascalCompiler/Grammar/Terminals.i

# target to preprocess a source file
source/src/PascalCompiler/Grammar/Terminals.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/Grammar/Terminals.cpp.i
.PHONY : source/src/PascalCompiler/Grammar/Terminals.cpp.i

source/src/PascalCompiler/Grammar/Terminals.s: source/src/PascalCompiler/Grammar/Terminals.cpp.s
.PHONY : source/src/PascalCompiler/Grammar/Terminals.s

# target to generate assembly for a file
source/src/PascalCompiler/Grammar/Terminals.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/Grammar/Terminals.cpp.s
.PHONY : source/src/PascalCompiler/Grammar/Terminals.cpp.s

source/src/PascalCompiler/IR/ArrayTypeInfo.o: source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/ArrayTypeInfo.o

# target to build an object file
source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.o

source/src/PascalCompiler/IR/ArrayTypeInfo.i: source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/ArrayTypeInfo.i

# target to preprocess a source file
source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.i

source/src/PascalCompiler/IR/ArrayTypeInfo.s: source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/ArrayTypeInfo.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/ArrayTypeInfo.cpp.s

source/src/PascalCompiler/IR/BasicTypeInfo.o: source/src/PascalCompiler/IR/BasicTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/BasicTypeInfo.o

# target to build an object file
source/src/PascalCompiler/IR/BasicTypeInfo.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/BasicTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/BasicTypeInfo.cpp.o

source/src/PascalCompiler/IR/BasicTypeInfo.i: source/src/PascalCompiler/IR/BasicTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/BasicTypeInfo.i

# target to preprocess a source file
source/src/PascalCompiler/IR/BasicTypeInfo.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/BasicTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/BasicTypeInfo.cpp.i

source/src/PascalCompiler/IR/BasicTypeInfo.s: source/src/PascalCompiler/IR/BasicTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/BasicTypeInfo.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/BasicTypeInfo.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/BasicTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/BasicTypeInfo.cpp.s

source/src/PascalCompiler/IR/Context.o: source/src/PascalCompiler/IR/Context.cpp.o
.PHONY : source/src/PascalCompiler/IR/Context.o

# target to build an object file
source/src/PascalCompiler/IR/Context.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/Context.cpp.o
.PHONY : source/src/PascalCompiler/IR/Context.cpp.o

source/src/PascalCompiler/IR/Context.i: source/src/PascalCompiler/IR/Context.cpp.i
.PHONY : source/src/PascalCompiler/IR/Context.i

# target to preprocess a source file
source/src/PascalCompiler/IR/Context.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/Context.cpp.i
.PHONY : source/src/PascalCompiler/IR/Context.cpp.i

source/src/PascalCompiler/IR/Context.s: source/src/PascalCompiler/IR/Context.cpp.s
.PHONY : source/src/PascalCompiler/IR/Context.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/Context.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/Context.cpp.s
.PHONY : source/src/PascalCompiler/IR/Context.cpp.s

source/src/PascalCompiler/IR/CustomTypeInfo.o: source/src/PascalCompiler/IR/CustomTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/CustomTypeInfo.o

# target to build an object file
source/src/PascalCompiler/IR/CustomTypeInfo.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/CustomTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/CustomTypeInfo.cpp.o

source/src/PascalCompiler/IR/CustomTypeInfo.i: source/src/PascalCompiler/IR/CustomTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/CustomTypeInfo.i

# target to preprocess a source file
source/src/PascalCompiler/IR/CustomTypeInfo.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/CustomTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/CustomTypeInfo.cpp.i

source/src/PascalCompiler/IR/CustomTypeInfo.s: source/src/PascalCompiler/IR/CustomTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/CustomTypeInfo.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/CustomTypeInfo.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/CustomTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/CustomTypeInfo.cpp.s

source/src/PascalCompiler/IR/EnumerationTypeInfo.o: source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/EnumerationTypeInfo.o

# target to build an object file
source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.o

source/src/PascalCompiler/IR/EnumerationTypeInfo.i: source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/EnumerationTypeInfo.i

# target to preprocess a source file
source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.i

source/src/PascalCompiler/IR/EnumerationTypeInfo.s: source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/EnumerationTypeInfo.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/EnumerationTypeInfo.cpp.s

source/src/PascalCompiler/IR/GlobalContext.o: source/src/PascalCompiler/IR/GlobalContext.cpp.o
.PHONY : source/src/PascalCompiler/IR/GlobalContext.o

# target to build an object file
source/src/PascalCompiler/IR/GlobalContext.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/GlobalContext.cpp.o
.PHONY : source/src/PascalCompiler/IR/GlobalContext.cpp.o

source/src/PascalCompiler/IR/GlobalContext.i: source/src/PascalCompiler/IR/GlobalContext.cpp.i
.PHONY : source/src/PascalCompiler/IR/GlobalContext.i

# target to preprocess a source file
source/src/PascalCompiler/IR/GlobalContext.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/GlobalContext.cpp.i
.PHONY : source/src/PascalCompiler/IR/GlobalContext.cpp.i

source/src/PascalCompiler/IR/GlobalContext.s: source/src/PascalCompiler/IR/GlobalContext.cpp.s
.PHONY : source/src/PascalCompiler/IR/GlobalContext.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/GlobalContext.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/GlobalContext.cpp.s
.PHONY : source/src/PascalCompiler/IR/GlobalContext.cpp.s

source/src/PascalCompiler/IR/IntegerTypeInfo.o: source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/IntegerTypeInfo.o

# target to build an object file
source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.o

source/src/PascalCompiler/IR/IntegerTypeInfo.i: source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/IntegerTypeInfo.i

# target to preprocess a source file
source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.i

source/src/PascalCompiler/IR/IntegerTypeInfo.s: source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/IntegerTypeInfo.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/IntegerTypeInfo.cpp.s

source/src/PascalCompiler/IR/LabelInfo.o: source/src/PascalCompiler/IR/LabelInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/LabelInfo.o

# target to build an object file
source/src/PascalCompiler/IR/LabelInfo.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/LabelInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/LabelInfo.cpp.o

source/src/PascalCompiler/IR/LabelInfo.i: source/src/PascalCompiler/IR/LabelInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/LabelInfo.i

# target to preprocess a source file
source/src/PascalCompiler/IR/LabelInfo.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/LabelInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/LabelInfo.cpp.i

source/src/PascalCompiler/IR/LabelInfo.s: source/src/PascalCompiler/IR/LabelInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/LabelInfo.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/LabelInfo.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/LabelInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/LabelInfo.cpp.s

source/src/PascalCompiler/IR/Module.o: source/src/PascalCompiler/IR/Module.cpp.o
.PHONY : source/src/PascalCompiler/IR/Module.o

# target to build an object file
source/src/PascalCompiler/IR/Module.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/Module.cpp.o
.PHONY : source/src/PascalCompiler/IR/Module.cpp.o

source/src/PascalCompiler/IR/Module.i: source/src/PascalCompiler/IR/Module.cpp.i
.PHONY : source/src/PascalCompiler/IR/Module.i

# target to preprocess a source file
source/src/PascalCompiler/IR/Module.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/Module.cpp.i
.PHONY : source/src/PascalCompiler/IR/Module.cpp.i

source/src/PascalCompiler/IR/Module.s: source/src/PascalCompiler/IR/Module.cpp.s
.PHONY : source/src/PascalCompiler/IR/Module.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/Module.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/Module.cpp.s
.PHONY : source/src/PascalCompiler/IR/Module.cpp.s

source/src/PascalCompiler/IR/StructTypeInfo.o: source/src/PascalCompiler/IR/StructTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/StructTypeInfo.o

# target to build an object file
source/src/PascalCompiler/IR/StructTypeInfo.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/StructTypeInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/StructTypeInfo.cpp.o

source/src/PascalCompiler/IR/StructTypeInfo.i: source/src/PascalCompiler/IR/StructTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/StructTypeInfo.i

# target to preprocess a source file
source/src/PascalCompiler/IR/StructTypeInfo.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/StructTypeInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/StructTypeInfo.cpp.i

source/src/PascalCompiler/IR/StructTypeInfo.s: source/src/PascalCompiler/IR/StructTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/StructTypeInfo.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/StructTypeInfo.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/StructTypeInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/StructTypeInfo.cpp.s

source/src/PascalCompiler/IR/VarInfo.o: source/src/PascalCompiler/IR/VarInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/VarInfo.o

# target to build an object file
source/src/PascalCompiler/IR/VarInfo.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/VarInfo.cpp.o
.PHONY : source/src/PascalCompiler/IR/VarInfo.cpp.o

source/src/PascalCompiler/IR/VarInfo.i: source/src/PascalCompiler/IR/VarInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/VarInfo.i

# target to preprocess a source file
source/src/PascalCompiler/IR/VarInfo.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/VarInfo.cpp.i
.PHONY : source/src/PascalCompiler/IR/VarInfo.cpp.i

source/src/PascalCompiler/IR/VarInfo.s: source/src/PascalCompiler/IR/VarInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/VarInfo.s

# target to generate assembly for a file
source/src/PascalCompiler/IR/VarInfo.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/PascalCompiler/IR/VarInfo.cpp.s
.PHONY : source/src/PascalCompiler/IR/VarInfo.cpp.s

source/src/RegexAST/RegexASTAnnotationEvaluator.o: source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.o
.PHONY : source/src/RegexAST/RegexASTAnnotationEvaluator.o

# target to build an object file
source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.o
.PHONY : source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.o

source/src/RegexAST/RegexASTAnnotationEvaluator.i: source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.i
.PHONY : source/src/RegexAST/RegexASTAnnotationEvaluator.i

# target to preprocess a source file
source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.i
.PHONY : source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.i

source/src/RegexAST/RegexASTAnnotationEvaluator.s: source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.s
.PHONY : source/src/RegexAST/RegexASTAnnotationEvaluator.s

# target to generate assembly for a file
source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.s
.PHONY : source/src/RegexAST/RegexASTAnnotationEvaluator.cpp.s

source/src/RegexAST/RegexASTNode.o: source/src/RegexAST/RegexASTNode.cpp.o
.PHONY : source/src/RegexAST/RegexASTNode.o

# target to build an object file
source/src/RegexAST/RegexASTNode.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTNode.cpp.o
.PHONY : source/src/RegexAST/RegexASTNode.cpp.o

source/src/RegexAST/RegexASTNode.i: source/src/RegexAST/RegexASTNode.cpp.i
.PHONY : source/src/RegexAST/RegexASTNode.i

# target to preprocess a source file
source/src/RegexAST/RegexASTNode.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTNode.cpp.i
.PHONY : source/src/RegexAST/RegexASTNode.cpp.i

source/src/RegexAST/RegexASTNode.s: source/src/RegexAST/RegexASTNode.cpp.s
.PHONY : source/src/RegexAST/RegexASTNode.s

# target to generate assembly for a file
source/src/RegexAST/RegexASTNode.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTNode.cpp.s
.PHONY : source/src/RegexAST/RegexASTNode.cpp.s

source/src/RegexAST/RegexASTParser.o: source/src/RegexAST/RegexASTParser.cpp.o
.PHONY : source/src/RegexAST/RegexASTParser.o

# target to build an object file
source/src/RegexAST/RegexASTParser.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTParser.cpp.o
.PHONY : source/src/RegexAST/RegexASTParser.cpp.o

source/src/RegexAST/RegexASTParser.i: source/src/RegexAST/RegexASTParser.cpp.i
.PHONY : source/src/RegexAST/RegexASTParser.i

# target to preprocess a source file
source/src/RegexAST/RegexASTParser.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTParser.cpp.i
.PHONY : source/src/RegexAST/RegexASTParser.cpp.i

source/src/RegexAST/RegexASTParser.s: source/src/RegexAST/RegexASTParser.cpp.s
.PHONY : source/src/RegexAST/RegexASTParser.s

# target to generate assembly for a file
source/src/RegexAST/RegexASTParser.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/RegexAST/RegexASTParser.cpp.s
.PHONY : source/src/RegexAST/RegexASTParser.cpp.s

source/src/main.o: source/src/main.cpp.o
.PHONY : source/src/main.o

# target to build an object file
source/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/main.cpp.o
.PHONY : source/src/main.cpp.o

source/src/main.i: source/src/main.cpp.i
.PHONY : source/src/main.i

# target to preprocess a source file
source/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/main.cpp.i
.PHONY : source/src/main.cpp.i

source/src/main.s: source/src/main.cpp.s
.PHONY : source/src/main.s

# target to generate assembly for a file
source/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/source/src/main.cpp.s
.PHONY : source/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compiler"
	@echo "... source/src/PascalCompiler/Grammar/Nonterminals.o"
	@echo "... source/src/PascalCompiler/Grammar/Nonterminals.i"
	@echo "... source/src/PascalCompiler/Grammar/Nonterminals.s"
	@echo "... source/src/PascalCompiler/Grammar/Terminals.o"
	@echo "... source/src/PascalCompiler/Grammar/Terminals.i"
	@echo "... source/src/PascalCompiler/Grammar/Terminals.s"
	@echo "... source/src/PascalCompiler/IR/ArrayTypeInfo.o"
	@echo "... source/src/PascalCompiler/IR/ArrayTypeInfo.i"
	@echo "... source/src/PascalCompiler/IR/ArrayTypeInfo.s"
	@echo "... source/src/PascalCompiler/IR/BasicTypeInfo.o"
	@echo "... source/src/PascalCompiler/IR/BasicTypeInfo.i"
	@echo "... source/src/PascalCompiler/IR/BasicTypeInfo.s"
	@echo "... source/src/PascalCompiler/IR/Context.o"
	@echo "... source/src/PascalCompiler/IR/Context.i"
	@echo "... source/src/PascalCompiler/IR/Context.s"
	@echo "... source/src/PascalCompiler/IR/CustomTypeInfo.o"
	@echo "... source/src/PascalCompiler/IR/CustomTypeInfo.i"
	@echo "... source/src/PascalCompiler/IR/CustomTypeInfo.s"
	@echo "... source/src/PascalCompiler/IR/EnumerationTypeInfo.o"
	@echo "... source/src/PascalCompiler/IR/EnumerationTypeInfo.i"
	@echo "... source/src/PascalCompiler/IR/EnumerationTypeInfo.s"
	@echo "... source/src/PascalCompiler/IR/GlobalContext.o"
	@echo "... source/src/PascalCompiler/IR/GlobalContext.i"
	@echo "... source/src/PascalCompiler/IR/GlobalContext.s"
	@echo "... source/src/PascalCompiler/IR/IntegerTypeInfo.o"
	@echo "... source/src/PascalCompiler/IR/IntegerTypeInfo.i"
	@echo "... source/src/PascalCompiler/IR/IntegerTypeInfo.s"
	@echo "... source/src/PascalCompiler/IR/LabelInfo.o"
	@echo "... source/src/PascalCompiler/IR/LabelInfo.i"
	@echo "... source/src/PascalCompiler/IR/LabelInfo.s"
	@echo "... source/src/PascalCompiler/IR/Module.o"
	@echo "... source/src/PascalCompiler/IR/Module.i"
	@echo "... source/src/PascalCompiler/IR/Module.s"
	@echo "... source/src/PascalCompiler/IR/StructTypeInfo.o"
	@echo "... source/src/PascalCompiler/IR/StructTypeInfo.i"
	@echo "... source/src/PascalCompiler/IR/StructTypeInfo.s"
	@echo "... source/src/PascalCompiler/IR/VarInfo.o"
	@echo "... source/src/PascalCompiler/IR/VarInfo.i"
	@echo "... source/src/PascalCompiler/IR/VarInfo.s"
	@echo "... source/src/RegexAST/RegexASTAnnotationEvaluator.o"
	@echo "... source/src/RegexAST/RegexASTAnnotationEvaluator.i"
	@echo "... source/src/RegexAST/RegexASTAnnotationEvaluator.s"
	@echo "... source/src/RegexAST/RegexASTNode.o"
	@echo "... source/src/RegexAST/RegexASTNode.i"
	@echo "... source/src/RegexAST/RegexASTNode.s"
	@echo "... source/src/RegexAST/RegexASTParser.o"
	@echo "... source/src/RegexAST/RegexASTParser.i"
	@echo "... source/src/RegexAST/RegexASTParser.s"
	@echo "... source/src/main.o"
	@echo "... source/src/main.i"
	@echo "... source/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

